import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const appTitle = process.env.APP_TITLE?.trim() || "不喝芝麻油";

export const metadata: Metadata = {
  title: appTitle,
  description: "Generated by create next app",
};

const icpRecordNumber = process.env.NEXT_PUBLIC_ICP_RECORD_NUMBER?.trim();

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="zh-CN">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="flex min-h-dvh flex-col">
          <div className="flex-1">{children}</div>
          {icpRecordNumber ? (
            <footer className="border-t border-white/70 bg-white/30 px-4 py-3 text-center text-sm text-[#6b6270] backdrop-blur-sm">
              <a
                href="https://beian.miit.gov.cn/"
                target="_blank"
                rel="noopener noreferrer"
                aria-label={`前往工业和信息化部备案管理系统查询 ${icpRecordNumber}`}
                className="inline-flex min-h-11 items-center justify-center rounded-lg px-3 underline-offset-4 transition-colors hover:text-[#c45d78] hover:underline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-[#c45d78]"
              >
                {icpRecordNumber}
              </a>
            </footer>
          ) : null}
        </div>
      </body>
    </html>
  );
}
